-- Sample Data Insertion Script for Diet Planner
-- Run this after the database is set up to populate with test data

-- Insert sample users
INSERT INTO users (name, email, age, gender, weight, height, activity_level, diet_preference, health_goals) VALUES
('John Doe', 'john@example.com', 30, 'male', 75.5, 180.0, 'moderate', 'balanced', 'Weight loss and muscle gain'),
('Jane Smith', 'jane@example.com', 25, 'female', 60.0, 165.0, 'active', 'vegetarian', 'Maintain healthy weight'),
('Mike Johnson', 'mike@example.com', 35, 'male', 85.0, 175.0, 'sedentary', 'keto', 'Weight loss'),
('Sarah Wilson', 'sarah@example.com', 28, 'female', 55.0, 160.0, 'very_active', 'high_protein', 'Muscle building'),
('David Brown', 'david@example.com', 42, 'male', 90.0, 182.0, 'light', 'mediterranean', 'Heart health')
ON CONFLICT (email) DO NOTHING;

-- Insert sample diet plans (you can run this after generating plans through the app)
-- This is just an example structure - actual plans will be generated by the AI

-- Sample meal log entries
INSERT INTO meal_logs (user_id, meal_date, meal_type, meal_name, calories, protein, carbs, fat, consumed) VALUES
(1, CURRENT_DATE, 'breakfast', 'Oatmeal with berries', 300, 12, 45, 8, true),
(1, CURRENT_DATE, 'lunch', 'Grilled chicken salad', 450, 35, 15, 25, true),
(1, CURRENT_DATE, 'dinner', 'Salmon with vegetables', 550, 40, 20, 30, false),
(2, CURRENT_DATE, 'breakfast', 'Greek yogurt with nuts', 280, 20, 15, 18, true),
(2, CURRENT_DATE, 'lunch', 'Quinoa bowl', 380, 15, 55, 12, true)
ON CONFLICT DO NOTHING;

-- Display inserted data
SELECT 'Users:' as info;
SELECT id, name, email, age, gender, weight, diet_preference FROM users;

SELECT 'Meal Logs:' as info;
SELECT u.name, ml.meal_type, ml.meal_name, ml.calories, ml.consumed 
FROM meal_logs ml 
JOIN users u ON ml.user_id = u.id;

-- Show table counts
SELECT 'Table Summary:' as info;
SELECT 'users' as table_name, COUNT(*) as record_count FROM users
UNION ALL
SELECT 'diet_plans' as table_name, COUNT(*) as record_count FROM diet_plans
UNION ALL
SELECT 'meal_logs' as table_name, COUNT(*) as record_count FROM meal_logs;
