#!/bin/bash

echo "🚀 Production Deployment Checklist for Diet Planner"
echo "=================================================="

echo ""
echo "📋 Pre-deployment Checklist:"
echo "✅ Code pushed to GitHub"
echo "✅ Render account created"
echo "✅ Netlify account created"
echo "✅ Gemini API key ready"

echo ""
echo "🎯 Step 1: Deploy Backend to Render"
echo "1. Go to https://render.com"
echo "2. New Web Service → Connect GitHub"
echo "3. Configure:"
echo "   Name: diet-planner-api"
echo "   Environment: Python"
echo "   Root Directory: backend"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: ./start-render.sh"

echo ""
echo "🎯 Step 2: Environment Variables (Render)"
echo "Set these in Render dashboard:"
echo "   APP_ENV=production"
echo "   FLASK_SECRET_KEY=[Auto-generate]"
echo "   JWT_SECRET_KEY=[Auto-generate]"
echo "   GEMINI_API_KEY=[Your key]"
echo "   CORS_ORIGINS=https://diet-planner.netlify.app"

echo ""
echo "🎯 Step 3: Create PostgreSQL Database"
echo "1. New Database → PostgreSQL"
echo "2. Name: diet-planner-db"
echo "3. Connect to web service"

echo ""
echo "🎯 Step 4: Deploy Frontend to Netlify"
echo "1. Go to https://netlify.com"
echo "2. New site from Git → Connect GitHub"
echo "3. Configure:"
echo "   Base directory: frontend"
echo "   Build command: npm run build"
echo "   Publish directory: frontend/build"

echo ""
echo "🎯 Step 5: Environment Variables (Netlify)"
echo "Set these in Netlify dashboard:"
echo "   REACT_APP_API_URL=https://diet-planner-api.onrender.com/api"
echo "   NODE_VERSION=18"

echo ""
echo "🎯 Step 6: Test Deployment"
echo "1. Open https://diet-planner.netlify.app"
echo "2. Test registration/login"
echo "3. Test diet plan generation"
echo "4. Verify all features work"

echo ""
echo "🎉 Deployment Complete!"
echo "Frontend: https://diet-planner.netlify.app"
echo "Backend:  https://diet-planner-api.onrender.com"
echo "Health:   https://diet-planner-api.onrender.com/api/health"

echo ""
echo "📚 For detailed instructions, see: DEPLOYMENT.md"
